raw_data_dir: /mnt/shared/projects/jhi/soil-ecology/202307_root2res-pilot-ONT
dorado_path: /mnt/shared/scratch/msmith/apps/dorado-0.3.2-linux-x64/bin/dorado
dorado_model: /mnt/shared/scratch/msmith/apps/dorado-0.3.2-linux-x64/models/dna_r10.4.1_e8.2_400bps_sup@v4.2.0
